name: podman

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '5 8 * * 0'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Containerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/legitcamper/toolbox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to gh Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build container image (latest tag)
        uses: redhat-actions/buildah-build@v2
        with:
          platforms: ${{ env.platforms }}
          context: ${{ env.distro }}/${{ matrix.release }}
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          containerfiles: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          oci: true

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          tags: latest

      - name: Push to Container Registry (latest tag)
        uses: redhat-actions/push-to-registry@v2
        id: push-latest
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          tags: latest
